---
baseURL: "https://cnheider.github.io"
title: Incoherent Subjects
paginate: 5
theme: "PaperMod"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-123-45
publishDir: "docs"
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: Incoherent Subjects
  description: Ideas, concepts and stuff..
  author: Me
  images:
    - "images/site/logo.png"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  disableSpecial1stPost: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false
  assets:
    favicon: "images/site/favicon.ico"
    favicon16x16: "images/site/favicon.ico"
    favicon32x32: "images/site/favicon.ico"
    apple_touch_icon: "images/site/favicon.ico"
    safari_pinned_tab: "images/site/favicon.ico"
  label:
    text: Home
    icon: "images/site/logo.png"
    iconHeight: 35
  profileMode:
    enabled: false
    title: ExampleSite
    subtitle: This is subtitle
    imageUrl: "images/site/logo.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog
  socialIcons:
    - name: github
      url: https://github.com/cnheider
  analytics:
    google:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
menu:
  main:
    - url: "/tags/"
      name: tags
      weight: 2
      identifier: tags
    - url: "/categories/"
      name: categories
      weight: 1
      identifier: categories
